/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PubliqueRouteImport } from './routes/publique'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as ColunistasIndexRouteImport } from './routes/colunistas.index'
import { Route as ColunistasInscricaoRouteImport } from './routes/colunistas.inscricao'
import { Route as MateriaSlugRouteImport } from './routes/materia.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PubliqueRoute = PubliqueRouteImport.update({
  id: '/publique',
  path: '/publique',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ColunistasIndexRoute = ColunistasIndexRouteImport.update({
  id: '/colunistas/',
  path: '/colunistas/',
  getParentRoute: () => rootRouteImport,
} as any)
const ColunistasInscricaoRoute = ColunistasInscricaoRouteImport.update({
  id: '/colunistas/inscricao',
  path: '/colunistas/inscricao',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriaSlugRoute = MateriaSlugRouteImport.update({
  id: '/materia/$slug',
  path: '/materia/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/publique': typeof PubliqueRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/colunistas/inscricao': typeof ColunistasInscricaoRoute
  '/materia/$slug': typeof MateriaSlugRoute
  '/colunistas/': typeof ColunistasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/publique': typeof PubliqueRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/colunistas/inscricao': typeof ColunistasInscricaoRoute
  '/materia/$slug': typeof MateriaSlugRoute
  '/colunistas': typeof ColunistasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/publique': typeof PubliqueRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/colunistas/inscricao': typeof ColunistasInscricaoRoute
  '/materia/$slug': typeof MateriaSlugRoute
  '/colunistas/': typeof ColunistasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/publique'
    | '/categoria/$slug'
    | '/colunistas/inscricao'
    | '/materia/$slug'
    | '/colunistas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/publique'
    | '/categoria/$slug'
    | '/colunistas/inscricao'
    | '/materia/$slug'
    | '/colunistas'
  id:
    | '__root__'
    | '/'
    | '/publique'
    | '/categoria/$slug'
    | '/colunistas/inscricao'
    | '/materia/$slug'
    | '/colunistas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PubliqueRoute: typeof PubliqueRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  ColunistasInscricaoRoute: typeof ColunistasInscricaoRoute
  MateriaSlugRoute: typeof MateriaSlugRoute
  ColunistasIndexRoute: typeof ColunistasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publique': {
      id: '/publique'
      path: '/publique'
      fullPath: '/publique'
      preLoaderRoute: typeof PubliqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colunistas/': {
      id: '/colunistas/'
      path: '/colunistas'
      fullPath: '/colunistas/'
      preLoaderRoute: typeof ColunistasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colunistas/inscricao': {
      id: '/colunistas/inscricao'
      path: '/colunistas/inscricao'
      fullPath: '/colunistas/inscricao'
      preLoaderRoute: typeof ColunistasInscricaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materia/$slug': {
      id: '/materia/$slug'
      path: '/materia/$slug'
      fullPath: '/materia/$slug'
      preLoaderRoute: typeof MateriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PubliqueRoute: PubliqueRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  ColunistasInscricaoRoute: ColunistasInscricaoRoute,
  MateriaSlugRoute: MateriaSlugRoute,
  ColunistasIndexRoute: ColunistasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
